name: CI

on: [pull_request] # TODO: also `master`

env:
  IMAGE_TAG: github.sha

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker images
      run: |
        set -e
        TARGET=prod make build
        TARGET=dev make build

    - name: Smoke tests
      run: |
        set -e
        TARGET=prod .travis/smoke-test.sh
        TARGET=dev .travis/smoke-test.sh

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Analyse
      run: .travis/analyse.sh
