name: CI

on: [push, pull_request]

#[10:02:05][giorgio@Newton:~/code/article-store]$ docker save -o article-store.master-dev libero/article-store:master-dev
#[10:02:35][giorgio@Newton:~/code/article-store]$ ls -l article-store.master-dev
#-rw------- 1 giorgio giorgio 213813248 Dec  3 10:02 article-store.master-dev
#[10:02:45][giorgio@Newton:~/code/article-store]$ docker load -i article-store.master-dev

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker images
      run: |
        set -e
        TARGET=prod make build
        TARGET=dev make build
        docker save -o docker-image-prod/article-store.tar libero/article-store:${IMAGE_TAG}
        docker save -o docker-image-dev/article-store.tar libero/article-store:${IMAGE_TAG}-dev

    - name: Upload prod Docker image
      uses: actions/upload-artifact@v1
      with:
        name: docker-image-prod
        path: docker-image-prod

    - name: Upload dev Docker image
      uses: actions/upload-artifact@v1
      with:
        name: docker-image-dev
        path: docker-image-dev


  lint:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Docker image artifact
      uses: actions/download-artifact@v1
      with:
        name: docker-image-dev

    - name: Test
      run: |
        set -e
        docker load -i docker-image-dev/article-store.tar
        make lint


  test:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Docker image artifact
      uses: actions/download-artifact@v1
      with:
        name: docker-image-dev

    - name: Test
      run: |
        set -e
        docker load -i docker-image-dev/article-store.tar
        make test


  smoke-tests-prod:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Docker image artifact
      uses: actions/download-artifact@v1
      with:
        name: docker-image-prod

    - name: Prod
      run: |
        set -e
        docker load -i docker-image-prod/article-store.tar
        TARGET=prod .travis/smoke-test.sh


  smoke-tests-dev:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Docker image artifact
      uses: actions/download-artifact@v1
      with:
        name: docker-image-dev

    - name: Dev
      run: |
        set -e
        docker load -i docker-image-dev/article-store.tar
        TARGET=dev .travis/smoke-test.sh


  analyse:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Docker image artifact
      uses: actions/download-artifact@v1
      with:
        name: docker-image-dev

    - name: Analyse
      run: |
        set -e
        docker load -i docker-image-dev/article-store.tar
        .travis/analyse.sh
