name: CI

on: [pull_request] # TODO: also `master`

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker images
      run: |
        set -e
        TARGET=prod make build
        TARGET=dev make build

    - name: Step 2
      run: |
        set -e
        echo "answer is 42"
