name: CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - master

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Docker images
      run: |
        TARGET=prod make build
        TARGET=dev make build

    - name: Lint
      run: make lint
      if: success() || failure()

    - name: Test
      run: make test && false
      if: success() || failure()

    - name: Smoke tests
      run: |
        TARGET=prod .travis/smoke-test.sh
        TARGET=dev .travis/smoke-test.sh
      if: success() || failure()

    - name: Analyse
      run: .travis/analyse.sh
