name: CI

on: [push, pull_request]

env:
  IMAGE_TAG: github.sha

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker images
      run: |
        set -e
        TARGET=prod make build
        TARGET=dev make build

    - name: Lint
      run: make lint
      if: always()

    - name: Test
      run: make test
      if: always()

    - name: Smoke tests
      run: |
        set -e
        TARGET=prod .travis/smoke-test.sh
        TARGET=dev .travis/smoke-test.sh
      if: always()

    - name: Analyse
      run: .travis/analyse.sh
